spring:
  application:
    name: ecommerce-website
    version: 1.0.0

  data:
    redis:
      host: "${REDIS_HOST:localhost}"
      port: "${REDIS_PORT:6379}"
  cache:
    type: redis
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 200MB

logging:
  level:
    sql: DEBUG
    hrynowieckip: DEBUG
