spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:ecommercewebsite
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2

  flyway:
    locations: classpath:db/migration
    enabled: true